/*
 * generated by Xtext
 */
package de.jpwinkler.daf.workflowdsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WorkflowDslRuntimeModule extends de.jpwinkler.daf.workflowdsl.AbstractWorkflowDslRuntimeModule {

}
