/*
* generated by Xtext
*/
package de.jpwinkler.daf.workflowdsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class WorkflowDslStandaloneSetup extends WorkflowDslStandaloneSetupGenerated{

	public static void doSetup() {
		new WorkflowDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

