<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cockpit" nsURI="de.jpwinkler.daf.fap5.model.cockpit" nsPrefix="cockpit">
  <eClassifiers xsi:type="ecore:EClass" name="CockpitModel" eSuperTypes="../../dafcore/model/common.ecore#//ModelObject">
    <eOperations name="findMapping" eType="#//FunctionContributionTargetMapping">
      <eParameters name="fct" eType="ecore:EClass components_systems.ecore#//FunctionContributionTarget"/>
    </eOperations>
    <eOperations name="findFunctionContributionTargets" upperBound="-1" eType="ecore:EClass components_systems.ecore#//FunctionContributionTarget">
      <eParameters name="cbm" eType="ecore:EClass codebeamer.ecore#//CodeBeamerModel"/>
    </eOperations>
    <eOperations name="getIssueTypes" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getIssues" upperBound="-1" eType="ecore:EClass codebeamer.ecore#//Issue">
      <eParameters name="issueType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
        eType="#//FunctionContributionTargetMapping" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicleFunctionProgress"
        upperBound="-1" eType="#//VehicleFunctionProgress" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="documents" upperBound="-1"
        eType="ecore:EClass codebeamer.ecore#//CodeBeamerModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VehicleFunctionProgress" eSuperTypes="../../dafcore/model/common.ecore#//ModelObject">
    <eOperations name="isSpecified" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isMapped" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="getProgress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eOperations name="getEstimatedRemainingWork" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eOperations name="getSpecifiedFunctionContributionCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eOperations name="getTotalFunctionContributionCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicleFunction" eType="ecore:EClass srs.ecore#//VehicleFunction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cockpitModel" eType="#//CockpitModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subFunctionProgress" upperBound="-1"
        eType="#//VehicleFunctionProgress" containment="true" eOpposite="#//VehicleFunctionProgress/parentProgress"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentProgress" eType="#//VehicleFunctionProgress"
        eOpposite="#//VehicleFunctionProgress/subFunctionProgress"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionContributionProgress"
        upperBound="-1" eType="#//FunctionContributionProgress" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionContributionTargetMapping" eSuperTypes="../../dafcore/model/common.ecore#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionContributionTarget"
        eType="ecore:EClass components_systems.ecore#//FunctionContributionTarget"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="documents" upperBound="-1"
        eType="ecore:EClass codebeamer.ecore#//CodeBeamerModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionContributionProgress" eSuperTypes="../../dafcore/model/common.ecore#//ModelObject">
    <eOperations name="isMapped" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isSpecified" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="getExstimatedRemainingWork" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionContribution" eType="ecore:EClass srs.ecore#//FunctionContribution"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cockpitModel" eType="#//CockpitModel"/>
  </eClassifiers>
</ecore:EPackage>
