<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="componentssystems" nsURI="de.jpwinkler.daf.fap5.model.componentssystems"
    nsPrefix="componentssystems">
  <eClassifiers xsi:type="ecore:EClass" name="ComponentsSystemsModel" eSuperTypes="../../dafcore/model/common.ecore#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionContributionTargets"
        upperBound="-1" eType="#//FunctionContributionTarget" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionContributionTarget" eSuperTypes="../../dafcore/model/common.ecore#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="acronym" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responsibility" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="department" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contributions" upperBound="-1"
        eType="ecore:EClass srs.ecore#//FunctionContribution" eOpposite="srs.ecore#//FunctionContribution/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="#//FunctionContributionTarget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionalities" upperBound="-1"
        eType="#//Functionality" eOpposite="#//Functionality/system"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//FunctionContributionTarget"/>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalComponent" eSuperTypes="#//FunctionContributionTarget"/>
  <eClassifiers xsi:type="ecore:EClass" name="Functionality" eSuperTypes="#//FunctionContributionTarget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="system" eType="#//System"
        eOpposite="#//System/functionalities"/>
  </eClassifiers>
</ecore:EPackage>
