<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="srs" nsURI="de.jpwinkler.daf.fap5.model.srs" nsPrefix="srs">
  <eClassifiers xsi:type="ecore:EClass" name="SRSModel" eSuperTypes="../../dafcore/model/common.ecore#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicleFunctions" upperBound="-1"
        eType="#//VehicleFunction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VehicleFunction" eSuperTypes="#//FunctionalSpecificationContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//VehicleFunctionType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subFunctions" upperBound="-1"
        eType="#//VehicleFunction" containment="true" eOpposite="#//VehicleFunction/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//VehicleFunction"
        eOpposite="#//VehicleFunction/subFunctions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionContribution" eSuperTypes="#//FunctionalSpecificationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass components_systems.ecore#//FunctionContributionTarget"
        eOpposite="components_systems.ecore#//FunctionContributionTarget/contributions"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VehicleFunctionType">
    <eLiterals name="CUSTOMER_FUNCTION"/>
    <eLiterals name="SUPPORTING_FUNCTION"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalSpecificationContainer" eSuperTypes="#//FunctionalSpecificationElement">
    <eOperations name="getFunctionContributions" upperBound="-1" eType="#//FunctionContribution"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//FunctionalSpecificationElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalSpecificationElement" abstract="true"
      eSuperTypes="../../dafcore/model/common.ecore#//ModelObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="Precondition" eSuperTypes="#//FunctionalSpecificationContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndCondition" eSuperTypes="#//FunctionalSpecificationContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trigger" eSuperTypes="#//FunctionalSpecificationContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Heading" eSuperTypes="#//FunctionalSpecificationContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Description" eSuperTypes="#//FunctionalSpecificationElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
