/*
 * generated by Xtext
 */
package de.jpwinkler.daf.workflowdsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractWorkflowDslValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(de.jpwinkler.daf.workflowdsl.workflowDsl.WorkflowDslPackage.eINSTANCE);
		return result;
	}
}
