/*
* generated by Xtext
*/
package de.jpwinkler.daf.workflowdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class WorkflowDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/jpwinkler/daf/workflowdsl/parser/antlr/internal/InternalWorkflowDsl.tokens");
	}
}
