<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="de.jpwinkler.daf.model" nsPrefix="Doors">
    <eClassifiers xsi:type="ecore:EClass" name="DoorsDB">
        <eOperations name="accept">
            <eParameters name="visitor" eType="#//DoorsTreeNodeVisitor"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="root" eType="#//DoorsFolder"
                             containment="true"/>
    </eClassifiers>
  
    <eClassifiers xsi:type="ecore:EClass" name="DoorsDatabaseVersion">
        <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="#//DoorsModule"
                             eOpposite="#//DoorsModule/versions"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
                             eType="#//StringToStringMap" containment="true"/>
    </eClassifiers>
  
    <eClassifiers xsi:type="ecore:EClass" name="DoorsFolder" eSuperTypes="#//DoorsTreeNode">
        <eOperations name="getFolder" eType="#//DoorsFolder">
            <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eOperations>
        <eOperations name="getModule" eType="#//DoorsModule">
            <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eOperations>
    </eClassifiers>
    
    
    <eClassifiers xsi:type="ecore:EClass" name="DoorsModule" eSuperTypes="#//DoorsTreeNode">
        <eOperations name="findAttributeDefinition" eType="#//AttributeDefinition">
            <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eOperations>
        <eOperations name="findObject" eType="#//DoorsObject">
            <eParameters name="objectIdentifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eOperations>
        
        <eOperations name="getLatestVersion" eType="#//DoorsDatabaseVersion"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="attributeDefinitions" upperBound="-1"
                             eType="#//AttributeDefinition" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="view" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="versions" upperBound="-1"
                             eType="#//DoorsDatabaseVersion" containment="true" eOpposite="#//DoorsDatabaseVersion/module"/>
    </eClassifiers>
  
    <eClassifiers xsi:type="ecore:EClass" name="DoorsObject" eSuperTypes="#//DoorsTreeNode">
        <eOperations name="isHeading" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
            <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
                <details key="body" value="return getObjectHeading() != null &amp;&amp; !getObjectHeading().isEmpty();"/>
            </eAnnotations>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectIdentifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
                             volatile="true" transient="true" defaultValueLiteral="" derived="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectLevel" unique="false"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" volatile="true"
                             transient="true" derived="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectNumber" unique="false"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" volatile="true"
                             transient="true" derived="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="absoluteNumber" unique="false"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" volatile="true"
                             transient="true" derived="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectText" unique="false"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" volatile="true"
                             transient="true" derived="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectShortText" unique="false"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" volatile="true"
                             transient="true" derived="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectHeading" unique="false"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" volatile="true"
                             transient="true" derived="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
                             volatile="true" transient="true" defaultValueLiteral="" derived="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingLinks" upperBound="-1"
                             eType="#//Link" containment="true" eOpposite="#//Link/source"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="incomingLinks" upperBound="-1"
                             eType="#//ResolvedLink" eOpposite="#//ResolvedLink/target"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="#//DoorsModule"/>
    </eClassifiers>
  
    <eClassifiers xsi:type="ecore:EClass" name="StringToStringMap" instanceClassName="java.util.Map$Entry">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  
    <eClassifiers xsi:type="ecore:EDataType" name="DoorsTreeNodeVisitor" instanceClassName="de.jpwinkler.daf.model.DoorsTreeNodeVisitor"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Pattern" instanceClassName="java.util.regex.Pattern"/>
    
    <eClassifiers xsi:type="ecore:EClass" name="Link" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//DoorsObject"
                             eOpposite="#//DoorsObject/outgoingLinks"/>
    </eClassifiers>  
    <eClassifiers xsi:type="ecore:EClass" name="ResolvedLink" eSuperTypes="#//Link">
        <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//DoorsObject"
                             eOpposite="#//DoorsObject/incomingLinks"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UnresolvedLink" eSuperTypes="#//Link">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetModule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetObject" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  
    <eClassifiers xsi:type="ecore:EClass" name="DoorsTreeNode">
        <eOperations name="accept">
            <eParameters name="visitor" eType="#//DoorsTreeNodeVisitor"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
                             eType="#//DoorsTreeNode" containment="true" resolveProxies="false" eOpposite="#//DoorsTreeNode/parent"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//DoorsTreeNode"
                             eOpposite="#//DoorsTreeNode/children"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" ordered="false"
                             upperBound="-1" eType="#//StringToStringMap" containment="true" resolveProxies="false"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
                             changeable="false" volatile="true" transient="true" derived="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullNameSegments" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
                             changeable="false" volatile="true" transient="true" derived="true" upperBound="-1"/>
        
        <eOperations name="hasTag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
            <eParameters name="tag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eOperations>
        
        <eOperations name="hasTag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
            <eParameters name="pattern" eType="#//Pattern"/>
        </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AttributeDefinition">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
</ecore:EPackage>
